name: btk_todo
description: "BTK ."
version: 1.0.0+1

environment:
  # Mimimum Dart SDK sürümü
  sdk: ^3.5.2

# Uygulamanın çalışması için gerekli olan temel paketler
# Sadece dependencies bölümünde belirtilen paketler 
# Derlenmiş projeye dahil edilir
dependencies:
  # Flutter SDK'sının projede kullanılacağını belirtir.
  flutter:
    sdk: flutter
  # Localization (L10N)
  flutter_localizations:
    sdk: flutter
  # Cupertino stili iOS ikonları
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.0
  injectable: ^2.5.0
  dartz: ^0.10.1
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.3.2
  formz: ^0.7.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1

# Geliştirme ve test süreçlerinde kullanılır
# Uygulamanın çalışması sırasında gerekli değildir.
# Derlenmiş projeye dahil edilmez.
dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  # Linting & Code Quality
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  very_good_analysis: ^6.0.0

# Flutter yapılandırma ayarları
flutter:
  # Material Design bileşenlerini kullan
  uses-material-design: true

  # Otomatik dosya üretimini etkinleştir
  generate: true 

  assets:
    - assets/logos/
    - assets/icons/

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true


  