name: btk_todo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
# Minumum Dart Sürümü
  sdk: ^3.5.2

# Uygulamanın çalışması için gerekli olan temel paketler
# Sadece dependencies kısmında yer alan paketler uygulamanın çalışması için yeterlidir.
dependencies:
# Flutter SDK'sının projede kullanılacağını belirtir.
  flutter:
    sdk: flutter
# Cupertiono stili iOS ikonları için kullanılır.
  cupertino_icons: ^1.0.8 
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

# Uygulamanın geliştirilmesi için gerekli olan paketler
# Bu paketler sadece geliştirme aşamasında kullanılır.
# Derlenmiş projeye dahil edilmez.
dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
# Linting & Code Quality
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true